id: P003263
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22373
  title: གསང་བདེ་འཇིགས་གསུམ་སོགས་དགེ་ལུགས་ཀྱི་ཆོ་ག
  author: ''
  volumes:
    823e8a122191404288750590ca536822:
      image_group_id: I1KG22389
      title: ''
      volume_number: 1
      total_pages: 696
