id: P003263
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:51:10.175949
source_metadata:
  id: bdr:W1KG22373
  title: གསང་བདེ་འཇིགས་གསུམ་སོགས་དགེ་ལུགས་ཀྱི་ཆོ་ག
  author: ''
  volumes:
    823e8a122191404288750590ca536822:
      image_group_id: I1KG22389
      title: ''
      volume_number: 1
      total_pages: 696
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
